services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/compras_development

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compras_development

volumes:
  bundle:
  pgdata:
