default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: compras_development

test:
  <<: *default
  database: compras_test
