# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856f38bf8cf83a8208efb89a45b8d7ca05c1a347300e7b2aca7c63805fdec7e1d848e189891589b815758a571877cdf79673aa03c8b5360b4a242b885569f688

test:
  secret_key_base: ec7a5909d9d60b0683e6ddd99b6a282efa1e56a4374ac473ac220c45231e55e3f0d7aac19448f7082fbb77d7157456c22e4bb792085c242d30e337f82ac9f68b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
